# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forms/ui/mainform.ui'
#
# Created by: PyQt5 UI code generator 5.8
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(640, 471)
        MainWindow.setMinimumSize(QtCore.QSize(400, 400))
        MainWindow.setMaximumSize(QtCore.QSize(1000, 1000))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 13, 111, 16))
        self.label.setObjectName("label")
        self.btn_choose_file = QtWidgets.QPushButton(self.centralwidget)
        self.btn_choose_file.setGeometry(QtCore.QRect(140, 10, 101, 23))
        self.btn_choose_file.setObjectName("btn_choose_file")
        self.groupBox_data = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_data.setEnabled(False)
        self.groupBox_data.setGeometry(QtCore.QRect(20, 50, 561, 291))
        self.groupBox_data.setObjectName("groupBox_data")
        self.label_2 = QtWidgets.QLabel(self.groupBox_data)
        self.label_2.setGeometry(QtCore.QRect(10, 23, 31, 16))
        self.label_2.setObjectName("label_2")
        self.comboBox_list = QtWidgets.QComboBox(self.groupBox_data)
        self.comboBox_list.setGeometry(QtCore.QRect(70, 20, 121, 22))
        self.comboBox_list.setObjectName("comboBox_list")
        self.groupBox_large_sample = QtWidgets.QGroupBox(self.groupBox_data)
        self.groupBox_large_sample.setGeometry(QtCore.QRect(40, 70, 211, 101))
        self.groupBox_large_sample.setObjectName("groupBox_large_sample")
        self.label_4 = QtWidgets.QLabel(self.groupBox_large_sample)
        self.label_4.setGeometry(QtCore.QRect(10, 61, 71, 16))
        self.label_4.setObjectName("label_4")
        self.label_3 = QtWidgets.QLabel(self.groupBox_large_sample)
        self.label_3.setGeometry(QtCore.QRect(30, 33, 47, 13))
        self.label_3.setObjectName("label_3")
        self.lineEdit_top_left = QtWidgets.QLineEdit(self.groupBox_large_sample)
        self.lineEdit_top_left.setGeometry(QtCore.QRect(90, 30, 113, 20))
        self.lineEdit_top_left.setObjectName("lineEdit_top_left")
        self.lineEdit_right_bottom = QtWidgets.QLineEdit(self.groupBox_large_sample)
        self.lineEdit_right_bottom.setGeometry(QtCore.QRect(90, 60, 113, 20))
        self.lineEdit_right_bottom.setObjectName("lineEdit_right_bottom")
        self.groupBox_small_sample = QtWidgets.QGroupBox(self.groupBox_data)
        self.groupBox_small_sample.setGeometry(QtCore.QRect(300, 70, 211, 101))
        self.groupBox_small_sample.setObjectName("groupBox_small_sample")
        self.label_5 = QtWidgets.QLabel(self.groupBox_small_sample)
        self.label_5.setGeometry(QtCore.QRect(10, 61, 71, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox_small_sample)
        self.label_6.setGeometry(QtCore.QRect(30, 33, 47, 13))
        self.label_6.setObjectName("label_6")
        self.lineEdit_top_left_2 = QtWidgets.QLineEdit(self.groupBox_small_sample)
        self.lineEdit_top_left_2.setGeometry(QtCore.QRect(90, 30, 113, 20))
        self.lineEdit_top_left_2.setObjectName("lineEdit_top_left_2")
        self.lineEdit__right_bottom = QtWidgets.QLineEdit(self.groupBox_small_sample)
        self.lineEdit__right_bottom.setGeometry(QtCore.QRect(90, 60, 113, 20))
        self.lineEdit__right_bottom.setObjectName("lineEdit__right_bottom")
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox_data)
        self.groupBox_4.setGeometry(QtCore.QRect(170, 190, 211, 80))
        self.groupBox_4.setObjectName("groupBox_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_5.setGeometry(QtCore.QRect(40, 30, 141, 20))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.btn_calc = QtWidgets.QPushButton(self.centralwidget)
        self.btn_calc.setEnabled(False)
        self.btn_calc.setGeometry(QtCore.QRect(240, 360, 141, 41))
        self.btn_calc.setObjectName("btn_calc")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Метод Пугачева"))
        self.label.setText(_translate("MainWindow", "Выберите имя файла:"))
        self.btn_choose_file.setText(_translate("MainWindow", "Выбрать файл"))
        self.groupBox_data.setTitle(_translate("MainWindow", "Данные для обработки:"))
        self.label_2.setText(_translate("MainWindow", "Лист:"))
        self.groupBox_large_sample.setTitle(_translate("MainWindow", "Большая выборка:"))
        self.label_4.setText(_translate("MainWindow", "RightBottom:"))
        self.label_3.setText(_translate("MainWindow", "TopLeft:"))
        self.groupBox_small_sample.setTitle(_translate("MainWindow", "Малая выборка:"))
        self.label_5.setText(_translate("MainWindow", "RightBottom:"))
        self.label_6.setText(_translate("MainWindow", "TopLeft:"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Ячейка результата:"))
        self.btn_calc.setText(_translate("MainWindow", "Расчитать"))

